server:
  port: 8201
spring:
  application:
    name: user-service

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 4000
    database:
      sync: 1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

knife4j:
  production: false
  basic:
    enable: true
    username: admin
    password: 123321